function database_init(){
	
	var database_schema={
			"shortname":"us.heiren.vitamintracking",
			"version":.01,
			"longname":"Vitamin Tracking Database",
			"size":500000,
			"tables":[
			          {
			        	  "table_name":"unit",
			        	  "fields":[
			        	            {
			        	            	"field_name":"id",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"name",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"abbreviation",
			        	            	"field_type":"TEXT"
			        	            }
			                    ]
			          },
			          {
			        	  "table_name":"vitamin",
			        	  "fields":[
			        	            {
			        	            	"field_name":"id",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"name",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"units",
			        	            	"field_type":"TEXT"
			        	            }
			                    ]
			          },
			          {
			        	  "table_name":"multivitamin",
			        	  "fields":[
			        	            {
			        	            	"field_name":"id",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"name",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"manufacturer",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"pills",
			        	            	"field_type":"FLOAT"
			        	            }
			                    ]
			          },
			          {
			        	  "table_name":"multivitamin_vitamins",
			        	  "fields":[
									{
										"field_name":"id",
										"field_type":"TEXT"
									},
			        	            {
			        	            	"field_name":"multivitamin_id",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"vitamin_id",
			        	            	"field_type":"TEXT"
			        	            },
			        	            {
			        	            	"field_name":"amount",
			        	            	"field_type":"FLOAT"
			        	            }
			                    ]
			          }
			          ]
	};
	database.initDb(database_schema);
};