UPDATE mysql.user SET Password=PASSWORD('Cm4rt!') WHERE User='root'; FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'Cm4rt!' WITH GRANT OPTION; FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' IDENTIFIED BY 'Cm4rt!' WITH GRANT OPTION; FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'Cm4rt!' WITH GRANT OPTION; FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'cmart'@'%' IDENTIFIED BY 'Cm4rt!' WITH GRANT OPTION; FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'cmart'@'127.0.0.1' IDENTIFIED BY 'Cm4rt!' WITH GRANT OPTION; FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'cmart'@'localhost' IDENTIFIED BY 'Cm4rt!' WITH GRANT OPTION; FLUSH PRIVILEGES;
CREATE DATABASE cmart;
FLUSH PRIVILEGES;